# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=255, verbose_name='Identificaci\xf3n (RUC o C.I.')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre y Apellido / Raz\xf3n Social')),
                ('telefono', models.CharField(max_length=255, verbose_name='Tel\xe9fono Fijo')),
                ('movil', models.CharField(max_length=255, verbose_name='Tel\xe9fono m\xf3vil')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electr\xf3nico')),
                ('tipo_personeria', models.CharField(choices=[('tipo 1', 'tipo 1'), ('tipo 2', 'tipo 2'), ('tipo 3', 'tipo 3'), ('tipo 4', 'tipo 4')], max_length=255, verbose_name='Tipo de personer\xeda')),
            ],
        ),
    ]
